### ISSUE TITLE
A small issue

### ISSUE THREAD

**Issue by ilovekishansambhi** [Gum-Joe/bedel#1]
Everything is fine except for the fact that you still haven't performed Whatcha Doin by Bluey and the Universe in public. You were meant to do this in Paris and you didn't. I am ashamed in you.

**Comment by Gum-Joe** [comment]
This is a programming site.

**Comment by Gum-Joe** [comment]
Hi Udayan

**Comment by Gum-Joe** [comment]
Learn to program and help me develop this, then I will

**Comment by Gum-Joe** [comment]
answer your request.
